gmeghnag/omc

- cmd/certs/certs.go
- cmd/certs/inspect.go
- cmd/certs/inspect_test.go
- cmd/get/certificate/certificatesigningrequest.go
- cmd/get/core/configmaps.go
- cmd/get/core/secrets.go
- cmd/helpers/helpers.go
- root/root.go
This adds an `omc certs inspect` command inspired by the similar command in https://github.com/openshift/cluster-debug-tools. Unfortunately importing it directly causes a dependency hell since we're using different versions of apimachinery and since cluster-debug-tools is not meant to be relied on I'm porting the logic here.
To get here, the relevant get(configmap/secret/csr) functions are refactored for re-usability (... and testability perhaps if we agree to take the same path for other getters).
@gmeghnag let me know what you think
> [WIP] add cert inspection command

- README.md
- cmd/certs/certs.go
- cmd/certs/inspect.go
- cmd/certs/inspect_test.go
- cmd/get/certificate/certificatesigningrequest.go
- cmd/get/core/configmaps.go
- cmd/get/core/secrets.go
This improves `certs inspect`:
- rework getters to return generic unstructured for easier json/yaml formatting
- check presence of multiple cert keys in objects
- rework `certs inspect` output to be "omc-native"
fixes #89
> improve cert inspect output

- cmd/helpers/helpers.go
- Provides default "Unknown" format diff string
- Prevents SIGSEGV when attempting to use uninitialized ResourceFile variable, such as when running "oc certs inspect" on inspect output.
> add error checking for os.Stat in helpers.GetAge

- README.md
- cmd/use/helpers.go
- cmd/use/use.go
Allow downloading remote must-gather tarballs. This can be helpful when inspecting e.g. CI logs. In addition, don't attempt to create a directory if extracting a tarball to the current directory.
> Support downloading and extracting tarballs

- root/root.go
Adds the following klog arguments, but hides all except v:
- v
- alsologtostderr
- log_backtrace_at
- log_dir
- log_file
- log_file_max_size
- logtostderr
- one_output
- skip_headers
- skip_log_headers
- stderrthreshold
- vmodule
- add_dir_header
> Integrate klog flags with Cobra

- cmd/get/get.go
- cmd/get/get_test.go
- testdata/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/fakeclusterscopedresources.operator.openshift.io.yaml
- testdata/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/fakenamespacescopedresources.operator.openshift.io.yaml
Handle empty resources list output similar to oc client.
fixes #129
> Improve handling empty resourcelist

- cmd/config/config.go
- cmd/config/config_test.go
- cmd/project.go
- cmd/use/testdata/useContext/must-gather-multipleNS.sample/namespaces/openshift-etcd/openshift-etcd.yaml
- cmd/use/testdata/useContext/must-gather-multipleNS.sample/namespaces/openshift-kube-apiserver/openshift-kube-apiserver.yaml
- cmd/use/testdata/useContext/must-gather-singleNS.sample/namespaces/openshift-etcd/openshift-etcd.yaml
- cmd/use/use.go
- cmd/use/use_test.go
- root/root.go
- types/types.go
- vars/vars.go
This PR does the following:
1. Add a new config item to configure user's default project in omc.json
```
$ rm -rf ~/.omc/omc.json
$ ./omc config --default-project="openshift-etcd"
$ cat ~/.omc/omc.json
{
"default_project": "openshift-etcd"
}
```
2. "omc use" will read user's omc.json and set context.project accordingly
```
$ ./omc use cmd/use/testdata/useContext/must-gather-multipleNS.sample
$ cat ~/.omc/omc.json
{
"id": "YNIUr8Xz",
"contexts": [
{
"id": "YNIUr8Xz",
"path": "/Users/cchen/Code/github/omc/cmd/use/testdata/useContext/must-gather-multipleNS.sample",
"current": "*",
"project": "openshift-etcd"
}
],
"default_project": "openshift-etcd"
}
$ ./omc project
Using project "openshift-etcd" on must-gather "/Users/cchen/Code/github/omc/cmd/use/testdata/useContext/must-gather-multipleNS.s …
```
> Add new config to configure default project, closes #149

- cmd/get/helpers.go
When a qualified resource name is used in `omc get`, the `<resourceType>` variable is used to set a value in the `vars.GetArgs` object [here](https://github.com/gmeghnag/omc/blob/9acc721d2bd51af167b0827dff60c768ba60d098/cmd/get/helpers.go#L15-L117). The code [here](https://github.com/gmeghnag/omc/blob/9acc721d2bd51af167b0827dff60c768ba60d098/cmd/get/get.go#L99-L109)  uses the value of `<resourceNamePlural>.<resourceGroup>` to retrieve this value. A mismatch between the values of `<resourceType>` and  `<resourceNamePlural>.<resourceGroup>` would cause the described bug in https://github.com/gmeghnag/omc/issues/154.
The resourceType variable is populated directly from the command line. Therefore, this mismatch will occur if the shortname or singular resource name is used as part of the …
> Fixes #154: Getting resources with singular/short names

- cmd/node-logs/node-logs.go
Added a description for the `node-logs` command, which is similar to the `oc adm node-logs` command description.
> Add description for node-logs command

- cmd/describe/describe.go
Added a description for the `describe` command, which is similar to the `oc describe` command description.
> Add description for describe command

- cmd/ovn/subnets.go
In upstream OVN "k8s.ovn.org/host-addresses" was renamed to "k8s.ovn.org/host-cidrs" in 4.14
https://github.com/ovn-org/ovn-kubernetes/pull/3915
```
omc ovn subnets
HOST/NODE                     ROLE                   HOST IPV6-ADDRESSES                                                      HOST IP-ADDRESSES                 PRIMARY IF-ADDRESS   HOST GATEWAY-IP         NODE SUBNET
ci-ln--l6zc2-master-0         control-plane,master   fd65:a1a7:60ad:1240:66d5:3dc:317f:ddab/64,fd65:a1a7:60ad:1240::12/127    10.37.202.17/25                   10.37.202.17/25      10.37.202.1,fe70::4d7   10.127.0.0/23,fd65:10:127::/64
ci-ln--l6zc2-master-1         control-plane,master   fd65:a1a7:60ad:1240:5d7a:f70f:ec53:77ac/64,fd65:a1a7:60ad:1240::30/127   10.37.202.116/25                  10.37.202.116/25 …
```
> add "k8s.ovn.org/host-cidrs" for OCP 4.14

- README.md
- cmd/haproxy/backends.go
- cmd/haproxy/backends_test.go
- cmd/haproxy/haproxy.go
- root/root.go
- testdata/ingress_controllers/default/router-default-abc123-a1b1c3/haproxy.config
- testdata/ingress_controllers/shard/router-default-xyz789-x7y8z9/haproxy.config
This parses routes from any `haproxy.config` file in a must-gather's `./ingress_controllers/` directory, providing an early insight in non openshift-* namespaces which are not included by default.
> add haproxy config parsing logic

- cmd/use/use.go
- cmd/use/use_test.go
Ensure the in-memory state of a must-gather/inspect's path and project are consistent with the context being used, regardless of wether the context is new.
Fixes #171
As I don't have the full context on the use of the global variables in the `vars` package, I advise reviewing if updating `vars.Namespace` has any impact elsewhere.
Unit tests are provided.
> Update in-memory namespace on use

- .github/workflows/build.yml
- cmd/upgrade/helpers.go
- cmd/upgrade/upgrade.go
This PR does the following things:
1. Create a temp file when upgrading the omc binary to fix #176 
2. Add M-series MacOS in the build workflow so that arm64 binary could be downloaded in the releases
> [Upgrade] Create temp file when upgrading, closes #176

- cmd/get/get.go
- cmd/get/known-resources.yaml
PodNetworkConnectivityChecks are saved in the must-gather under `<mg.path>/pod_network_connectivity_check/podnetworkconnectivitychecks.yaml`
This adds support to `omc` by allowing you to view them by running `omc get podnetworkconnectivitychecks -n openshift-diagnostics`
```bash
$ omc get podnetworkconnectivitychecks -n openshift-network-diagnostics
NAME                                                            AGE
network-check-source-10-to-kubernetes-default-service-cluster   239d
```
> Add support for PodNetworkConnectivityChecks

- cmd/node-logs/node-logs.go
When running `omc node-logs` it prints a questions "Is it possible to read..."
I made so small verbiage changes to make it clear what is expected.
> Update verbiage in node-logs.go

- cmd/get/get.go
This fixes:
```
$ omc get pods -n openshift-ingress
error: namespace openshift-ingress not found.
```
In MG's with "AppleDouble encoded Macintosh file" dot-prefixed files, e.g:
```
$ tree -a <mg-root>/namespaces/openshift-ingress/pods/
<mg-root>/namespaces/openshift-ingress/pods/
├── ._router-default-xxx-yyy
├── router-default-xxx-yyy
│   ├── ._router
│   ├── router
│   │   ├── ._router
│   │   └── router
│   │       ├── ._logs
│   │       └── logs
│   │           ├── ._current.log
│   │           ├── current.log
│   │           ├── ._previous.insecure.log
│   │           ├── previous.insecure.log
│   │           ├── ._previous.log
│   │           └── previous.log
│   ├── ._router-default-xxx-yyy.yaml
│   └── router-default-xxx-yyy.yaml
├── ._router-default-aaa-bbb
└── …
```
> fix erroring on dot-prefixed pod files

- cmd/get/get.go
- cmd/get/helpers.go
- cmd/get/helpers_test.go
This is a continuation on #187 since the issue turns out wider then initially thought.
This introduces a wrapper around `fs.ReadDir` to only return "valid" resource files/directories.
Also fixed #180.
> check resource file validity

- cmd/upgrade/helpers.go
Replacing os.Rename() with mv might hurt Non-Unix compatiblity, by looking at the Releases, omc doesn't support Windows platform. Comparing to adding fallback functions to Open, Copy and Delete, simply using mv perhaps to be an easy-to-understand solution.
> Replace os.Rename() with mv, closes #192

- cmd/get/get.go
- vars/vars.go
Add rudimentary support for `--sort-by` to allow output sorting based on specified JSON path value similar to `kubectl` and `oc`.
While this works as-is for manual use/testing undertaken, I do not currently have the time to spend to improve this further. If anyone would like to integrate or improve, please be welcome.
Issues:
- Keeps all objects in memory (under specific scopes), even when sort-by is not specified, which may increase memory usage during execution for large resource lists in some circumstances.
- Sorting logic is haphazardly integrated into a number of functions.
- Only sorted using string representation of the JSON path value, which may not work for some values (e.g. numbers)
---
A refactor of `get.go` to provide an interface to allow for extension may improve some of the …
> Add --sort-by support for get subcommand

- cmd/machineconfig/extract.go
This pull requests implements two improvements for the "machine-config extract" command:
* A better help text that outlines the required arguments
* The "--all" option for the "machine-config extract" command
In the past I had some issues with the "machine-config extract" command, where I was unsure what the argument needs to be. The help text change improves this.
Also, sometimes I want to extract all available MachineConfigs to my disk, to search for a certain content (for example using `grep` or similar). This change adds the "--all" option to "machine-config extract". For that `extractMachineConfig()` was moved to a separate function, then we use the cobra flag to determine if we need to iterate over all MachineConfigs (`extractAll`) or just a single file.
> Improvements for "machine-config extract" command
